chore: P4ADEV-787 machine 2 machine
pagopa/p4pa-doc pull request #20
Opened 2024-09-24 09:52 UTC by antocalo

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-24 10:01 UTC, antonioT90 requested changes

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +            ]
this cannot be more an enum but a free text field

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +          required: true
not more mandatory when grant_type is client_credentials (removing the mandatory requirement, we should check if its presence is checked by java code)

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +          required: true
not more mandatory when grant_type is client_credentials (removing the mandatory requirement, we should check if its presence is checked by java code)

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +          required: true
not more mandatory when grant_type is client_credentials (removing the mandatory requirement, we should check if its presence is checked by java code)

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +            ]
not more an enum

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +  /am/clients/{organizationIpaCode}:
I am not sure that "clients" is a Access Management entity...
I think it should still be an Authentication concept
```suggestion
  /auth/clients/{organizationIpaCode}:
```

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +            default: 10
a paged query could be an over-engineered feature?
I don't think we should have such a large number of clients...

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +                $ref: '#/components/schemas/Client'
This should return a list of data (if paged, with the detail of the page, but I think that this API could not be paged)

2024-09-24 10:01 UTC, antonioT90 commented on design/a2a/openapi.yml
> +                $ref: '#/components/schemas/Client'
MoreOver, let's use different model to return the Client data:
Client, with just the clientId
ClientDetail, return by the findById, which will return (and decrypt) the clientSecret, which will be mandatory

2024-10-07 16:32 UTC, LarissaASLeite approved these changes

2024-10-07 16:49 UTC, antonioT90 requested changes

2024-10-07 16:49 UTC, antonioT90 commented on design/a2a/openapi.yml
> +                $ref: '#/components/schemas/ClientDTO'
This API should not return the clientSecret

2024-10-14 08:30 UTC, antonioT90 approved these changes

2024-10-14 08:31 UTC, merged